### ISSUE TITLE
End to End encryption and data persistence

### ISSUE THREAD

**Issue by emmabukacek** [MonarchApp/monarch#31]
## Purpose
* For V1, I would like to encrypt messages for the users.
* Post V1, implementing end to end encryption would be swell.

## Questions
* If a user is reported, we may need to retrieve those messages to determine punishment. Do we ask for the reporter's discretion on showing us messages? Or do they specify specific messages or times?
* How do we want to implement E2E? Is E2E worth it yet?

So yeah, how are we storing user data? Maybe this? https://github.com/kleinernik/elixir-aes-cmac 
How would we do E2E? Signal's protocol looks awesome, but it looks like it's only natively implemented in Java and C. We could use Ports to run it in Elixir for a V1, but a long-term solution would probably be preferable in code that could run on the BEAM VM. Anyway, all discussion is super appreciated; I'm very green in this area.

**Comment by sethetter** [comment]
From what I understand, the Signal protocol is the way to go. Whatever it takes to make that happen would probably be ideal, but I have no idea what kind of technical undertaking that involves.

**Comment by emmabukacek** [comment]
@sethetter Sweet. Calling Signal code through Erlang ports is probably the best way to go, but if we see a _lot_ of traffic, we'll need to re-evaluate me thinks. My understanding is that if we use a Port, we can treat the Signal C binary as an Erlang process which essentially just supervises a literal process. The downside is that because it's not native Erlang, we don't really get the BEAM concurrency benefits. Plus I think we may have to worry about memory usage and clean up.

I know WhatsApp recently adopted Signal and their codebase is Erlang, so I'm curious to see if we can find some articles on the matter there too.

**Comment by jcbwlkr** [comment]
I had some ideas about using an encrypted storage system like [Vault](https://www.vaultproject.io/) for sensitive data. I'm not sure if it's really the right answer or not so I'm exploring it.

**Comment by emmabukacek** [comment]
@jcbwlkr Any news on Vault?

**Comment by emmabukacek** [comment]
No need for this conversation right now. Closing out.
